name: Test

on: [push, pull_request]

jobs:
  test:
    name: WP Test (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.2']
        wp-versions: ['latest']

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv
        coverage: none

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-progress
        npm install

    - name: Lint PHP
      run: npm run lint:php

    - name: Lint JS/CSS
      run: |
        npm run lint:js
        npm run lint:css

    - name: Install WordPress Test Suite
      run: |
        bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1 latest

    - name: Run PHPUnit
      run: vendor/bin/phpunit

    - name: Build Plugin ZIP
      run: |
        # Install production dependencies only
        composer install --no-dev --optimize-autoloader
        
        # Create a temporary directory for the build
        mkdir build
        mkdir build/wp-pfadi-manager
        
        # Copy files to the build directory
        rsync -av --exclude='build' --exclude='.git' --exclude='.github' --exclude='tests' --exclude='bin' --exclude='node_modules' --exclude='docker-compose.yml' --exclude='CONTRIBUTING.md' --exclude='.stylelintignore' --exclude='.gitignore' --exclude='.editorconfig' . build/wp-pfadi-manager/
        
        # Create ZIP file
        cd build
        zip -r ../wp-pfadi-manager.zip wp-pfadi-manager
        cd ..

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: wp-pfadi-manager-zip
        path: wp-pfadi-manager.zip
